### ISSUE TITLE
ModuleNotFoundError: No module named 'options'

### ISSUE THREAD

**Issue by geetumolbabu91** [ipc-lab/private-ml-for-health#1]
Google colab returning error 'ModuleNotFoundError: No module named 'options'' while running

**Comment by mmalekzadeh** [comment]
The error you get seems related to the directory you use to put the code there and the way you import modules.
The 'options' file is this one: https://github.com/ipc-lab/private-ml-for-health/blob/main/private_training/src/options.py

**Comment by geetumolbabu91** [comment]
Thank you
